export const theme = {
  colors: {
    background: '#FCF9F4',
    surface: '#FFFFFF',
    surfaceMuted: '#F6F3EE',
    primary: '#864D61',
    primarySoft: '#FAD1DE',
    secondary: '#695F00',
    secondarySoft: '#F9E534',
    tertiarySoft: '#DDF4DE',
    text: '#1C1C19',
    textMuted: '#6F6768',
    border: '#E6E2D9',
    danger: '#BA1A1A',
    youtube: '#D93025',
    youtubeSoft: '#FCE8E6',
    onPrimary: '#FFFFFF',
    successText: '#335F39',
    transparent: 'transparent',
    mood: {
      happy: '#F9E534',
      flutter: '#FAD1DE',
      pleasure: '#FFD9E4',
      peaceful: '#BDEFBE',
      normal: '#E5E2DD',
      tired: '#DDD8D1',
      sad: '#DCC5E8',
      anxiety: '#FFE0A8',
      anger: '#FFDAD6',
      gloom: '#C9D7F2',
      stress: '#F4C7D5',
      sleepy: '#D9D6E8',
      shock: '#FFE4B8',
      numb: '#E3E0DA',
      excited: '#CDECCF',
    },
  },
  spacing: {
    xxs: 3,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 28,
    xxxl: 40,
  },
  fontSize: {
    caption: 11,
    labelSmall: 12,
    label: 13,
    bodySmall: 14,
    body: 15,
    button: 16,
    subtitle: 17,
    titleSmall: 18,
    titleMedium: 19,
    title: 20,
    titleLarge: 24,
    headline: 26,
    display: 28,
    iconSmall: 18,
    icon: 22,
    iconLarge: 52,
    mood: 64,
  },
  lineHeight: {
    compact: 18,
    body: 22,
  },
  radius: {
    md: 12,
    lg: 20,
    xl: 28,
    pill: 999,
  },
} as const;
